# Generated by Django 3.2.7 on 2021-09-30 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('course_name',),
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('courses', models.ManyToManyField(through='Dashboard.Enrollment', to='Dashboard.Courses')),
            ],
            options={
                'ordering': ('user',),
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('profile', 'course')},
        ),
    ]
