# Generated by Django 3.2.7 on 2021-09-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='grades',
            name='user_course_pair_grades',
        ),
        migrations.AddConstraint(
            model_name='grades',
            constraint=models.UniqueConstraint(fields=('user', 'course', 'quiz'), name='user_course_quiz_grades'),
        ),
    ]
