# Generated by Django 3.2.7 on 2021-10-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_assignmentfiles_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
