# Generated by Django 3.2.7 on 2021-10-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_assignments_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='description',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
