# Generated by Django 3.2.7 on 2021-10-04 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_alter_assignments_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='grade',
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('quiz_name', models.CharField(blank=True, max_length=100, null=True)),
                ('feedback', models.CharField(blank=True, max_length=100, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.enrollment')),
            ],
            options={
                'unique_together': {('enrollment', 'quiz_name')},
            },
        ),
    ]
