# Generated by Django 3.2.7 on 2021-10-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_auto_20211004_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='isTeacher',
            field=models.BooleanField(default=False),
        ),
    ]
