# Generated by Django 3.2.7 on 2021-10-05 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_enrollment_isteacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='enrollment',
        ),
        migrations.AddField(
            model_name='assignments',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.courses'),
        ),
    ]
