# Generated by Django 3.2.7 on 2021-10-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_auto_20211005_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='isTeacher',
            field=models.BooleanField(default=True),
        ),
    ]
