# Generated by Django 3.2.7 on 2021-10-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_auto_20211004_0931'),
        ('Dashboard', '0009_alter_enrollment_isteacher'),
    ]

    operations = [
    ]
