# Generated by Django 3.2.7 on 2021-10-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_auto_20211018_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentfiles',
            name='filename',
        ),
        migrations.AlterField(
            model_name='assignmentfiles',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
