# Generated by Django 3.2.7 on 2021-10-14 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0011_auto_20211005_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentfiles',
            name='course',
            field=models.ForeignKey(default='CS101', on_delete=django.db.models.deletion.CASCADE, to='Dashboard.courses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmentfiles',
            name='profile',
            field=models.ForeignKey(default='Master', on_delete=django.db.models.deletion.CASCADE, to='Dashboard.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignmentfiles',
            name='file',
            field=models.FileField(upload_to='files/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
