# Generated by Django 3.2.7 on 2021-10-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0012_auto_20211014_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentfiles',
            name='course',
        ),
        migrations.RemoveField(
            model_name='assignmentfiles',
            name='profile',
        ),
        migrations.AlterField(
            model_name='assignmentfiles',
            name='file',
            field=models.FileField(upload_to='files/%Y/%m/%d'),
        ),
    ]
