# Generated by Django 3.2.7 on 2021-10-18 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_feedback'),
        ('Dashboard', '0012_auto_20211018_1145'),
    ]

    operations = [
    ]
