# Generated by Django 3.2.7 on 2021-10-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0012_auto_20211018_1145'),
        ('Dashboard', '0014_alter_assignmentfiles_file'),
    ]

    operations = [
    ]
