# Generated by Django 3.2.7 on 2021-10-18 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0014_auto_20211018_1650'),
        ('Dashboard', '0015_merge_20211018_1523'),
    ]

    operations = [
    ]
