# Generated by Django 3.2.7 on 2021-11-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0016_merge_20211018_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='assistant_adding_privilege',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courses',
            name='assistant_code',
            field=models.CharField(default='12345678', max_length=32),
        ),
        migrations.AddField(
            model_name='courses',
            name='assistant_creation_privilege',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courses',
            name='assistant_grading_privilege',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='isAssistant',
            field=models.BooleanField(default=False),
        ),
    ]
