# Generated by Django 3.2.7 on 2021-11-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0017_auto_20211112_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_id',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
