# Generated by Django 3.2.7 on 2021-11-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0019_assignmentcompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
