# Generated by Django 3.2.7 on 2021-11-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0019_assignmentcompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentfiles',
            name='marks',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='assignmentfiles',
            name='weightage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='marks',
            field=models.FloatField(default=0),
        ),
    ]
