# Generated by Django 3.2.7 on 2021-11-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0020_auto_20211113_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentfiles',
            name='weightage',
        ),
        migrations.AddField(
            model_name='assignments',
            name='weightage',
            field=models.FloatField(default=0),
        ),
    ]
