# Generated by Django 3.2.7 on 2021-11-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0021_auto_20211113_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='marks',
            field=models.FloatField(default=0, null=True),
        ),
    ]
