# Generated by Django 3.2.7 on 2021-11-23 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0023_merge_20211113_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('time_of_last_edit', models.TimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.profile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('time_of_last_edit', models.TimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.profile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.courses')),
                ('parent_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.message')),
            ],
        ),
    ]
