# Generated by Django 3.2.7 on 2021-11-24 13:08

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0025_alter_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_of_last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='replies',
            name='time_of_last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senders', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), size=None)),
                ('times', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(auto_now=True), size=None)),
                ('messages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=None)),
                ('person1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='Dashboard.profile')),
                ('person2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='Dashboard.profile')),
            ],
        ),
    ]
