# Generated by Django 3.2.7 on 2021-11-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0026_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='class_average',
            field=models.FloatField(default=0, null=True),
        ),
    ]
