# Generated by Django 3.2.7 on 2021-11-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0028_coursecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='discussion_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
