# Generated by Django 3.2.7 on 2021-11-24 13:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0029_remove_conversation_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(auto_now=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='senders',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_of_last_edit',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='replies',
            name='time_of_last_edit',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
