# Generated by Django 3.2.7 on 2021-11-28 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0030_auto_20211128_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='date_time_of_last_edit',
            new_name='dates_and_times',
        ),
    ]
