# Generated by Django 3.2.7 on 2021-11-24 13:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0031_auto_20211124_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(auto_now=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_of_last_edit',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='replies',
            name='time_of_last_edit',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
